### ISSUE TITLE
question

### ISSUE THREAD

**Issue by 1imy** [krishnap25/tRFA#1]
from wquantiles import median as weighted_median
where is wquantiles?

**Comment by JSparks7** [comment]
Hello, I am trying to run this project, but it seems to be not going smoothly.
When running the `gm.sh` file, the message `ps: unknown option -- o
Try 'ps -- help' for more information` 
Would you like to ask if you are successful in running this project?

**Comment by 1imy** [comment]
yes,and I can't run the project. So I choose other papers to read.

JSparks7 ***@***.***> 于2023年6月7日周三 20:58写道：

**Comment by krishnap25** [comment]
@1imy The [wquantiles package](https://github.com/nudomarinero/wquantiles) can be installed via pip: `pip install wquantiles`.

**Comment by krishnap25** [comment]
@JSparks7 What OS are you using? It works ok for me on Ubuntu 20.04. 

You may wish to try out [this file](https://github.com/krishnap25/tRFA/blob/main/models/scripts/femnist_linear/gm_sequential.sh) instead to sequentially run all the jobs. This does not use the `ps` command. In comparison, [this file](https://github.com/krishnap25/tRFA/blob/main/models/scripts/femnist_linear/gm.sh)) runs several jobs in parallel for faster execution.

**Comment by JSparks7** [comment]
@krishnap25 Thank you very much for your reply！
Considering that I can only use a Linux virtual machine (VMware) that cannot call the local GPU, I am attempting to use `PyCharm` with Git's `sh.exe` installed in Windows to run `.sh` files, but I am not sure if it is due to OS reasons that the commands in `.sh` may not execute smoothly. If Linux is necessary, is WSL (Windows Subsystem for Linux) feasible?
Looking forward to your reply~

**Comment by krishnap25** [comment]
The OS is probably the reason. Everything works fine on my Linux machine. I do not have a Windows machine, so I do not how to fix this.

A good way forward would be to use the scripts for reference commands that you run separately. The bash scripts such as gm.sh are just loops that launch different experiments with the correct hyperparameters (which are specified within the scripts).

For example, the first job in scripts/femnist_linear/gm.sh is

```
time python -u main.py ${main_args} $options --seed $seed --output_summary_file ${outf}_${aggregation_out}_${corruption}_${seed}
```

The arguments ${main_args} and $options and $seed are specified in the preceding lines. You could substitute those values here and run the command directly on your terminal. That way, you do not have to deal with the unpleasantness of the bash scripts.

Btw, I ran the linear model jobs here directly on CPUs and used GPUs only in the neutral net jobs.

**Comment by JSparks7** [comment]
@krishnap25 Nice to receive your reply!

When I switched to WSL (Ubuntu 20.04), the script execution was much smoother, but after executing `./scripts/sent140_inear/gm.sh`, I saw the following error in the `outputs` log, which seems to be an encoding error: 

> Traceback (most recent call last):
> File "main. py", line 787, in<module>
>   main()
> File "main. py", line 94, in main
>**Clients, corrupted_ Client_ Ids=setup_ Clients (args. dataset, modelname=args. model,
> File "main. py", line 464, in setup_ Clients
>**Clients, groups, train_ Data, test_ Data=read_ Data (train_data_dir, test_data_dir, split by user=split by user,
> File "/mnt/d/Project/FL/FLByTorch/tRFA main/tRFA main/models/utils/model_utils. py", line 59, in read_ Data
>**EMB_ Array, _, Vocab=get_ Word_ EMB_ Arr (VOCAB-DIR)
> File "/mnt/d/Project/FL/FLByTorch/tRFA main/tRFA main/models/utils/language_utils. py", line 127, in get_ Word_ EMB_ Arr
>**EMBS=json. load (inf)
> File "/root/miniconde3/envs/rfa/lib/python3.8/json/__init__. py", line 293, in load
>**Return loads (fp. read()),
> File "/root/mini conde3/envs/rfa/lib/python3.8/codes. py", line 322, in code
>**(result, recommended)=self_ Buffer_ Decode (data, self errors, final)
> Unicode DecodeError: 'utf-8' code can't decode byte 0xff in position 37748736: invalid start byte

**Comment by krishnap25** [comment]
That's good to hear.

The glove embeddings are needed to run the sent140 experiments. This looks like an error with the embeddings (they might be missing or corrupted). 

You can run this script to download them:
https://github.com/krishnap25/tRFA/blob/main/models/sent140/get_embs.sh

If you already downloaded them and you get this error, could you try deleting the old embeddings and running this script again?

**Comment by JSparks7** [comment]
@krishnap25 Thanks a lot! With your help, I can now successfully run, but I have some questions to ask you. What do those logs represent under `/outputs/sent140/`? For example, `log_gm_clean_x`, `log_gm_flip_0.1_x`, ` log_gm_flip_0.01_x`, `log_gm_gauss_0.1_x` What do the `clean`, `flip` etc. and the following two numbers represent here?

**Comment by krishnap25** [comment]
@JSparks7 That's great!

There are two types of files written in the output directory.

The first is the log that you can use to monitor the status of the experiments. The names of these files start with `log_`. You can see how these are named in the script gm.sh or mean.sh by looking at the name following the ">" in each command. For example, one name is  `${logf}_${aggregation_out}_${corruption}_${seed}`. The `flip_0.1` refers to 10% of the labels being flipped and `gauss_0.1` means that 10% of the updates are replaced by random Gaussian noise.

The second type of file written out starts with the prefix `output_`. This is a csv file of the various training and test metrics over the course of training. I used these files to make the plots shown in the paper.
