### ISSUE TITLE
No such file or directory: 'dataset_constants/femnist_train_mean_std'

### ISSUE THREAD

**Issue by zeng1in** [krishnap25/tRFA#2]
Hello, when I ran the femlist task of Torch version tRFA, I encountered an error：
`No such file or directory: 'dataset'_ Constants/memnist_ Train_ Mean_ Std``
I found the dataset_ The constants file contains only the file rent140.
How can I solve this problem?

**Comment by krishnap25** [comment]
Hi @zeng1in, thanks for pointing this out! I've added these files to the `dataset_constants` folder. 

These are simply the precomputed mean and std of the data for normalization.

Best,
Krishna

**Comment by JSparks7** [comment]
> Hello, when I ran the femlist task of Torch version tRFA, I encountered an error： `No such file or directory: 'dataset'_ Constants/memnist_ Train_ Mean_ Std`` I found the dataset_ The constants file contains only the file rent140. How can I solve this problem?

@zeng1in hello, have you ever successfully started the femnist task of Torch version tRFA?
